[project]
name = "vercel-fastapi-starter"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
  "fastapi>=0.115.0",
  "uvicorn>=0.34.0",
  "requests>=2.32.3",
  "python-multipart>=0.0.9",
  "psycopg2-binary>=2.9.9",
  "python-dotenv>=1.0.1",
  "pydantic>=2.10.6",
  "jinja2==3.1.4"
]
